set-option -sa terminal-overrides ",xterm*:Tc"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'andrewjstryker/tmux-airline'
set -g @plugin 'iggredible/tmux-colorful'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'pwittchen/tmux-plugin-battery'
set -g @plugin 'tmux-plugins/tmux-logging'

# Enable 256 colors
set -g default-terminal "screen-256color"

# Set the tmux color scheme
set -g @tmux_colorful_color_scheme 'https://coolors.co/f4f1de-e07a5f-3d405b-81b29a-f2cc8f'
# Set the theme (optional)
set -g @tmux_airline_theme 'simple'

# Turns on mouse support for tmux 
set -g mouse on

# Starts the windows and panes from number 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set the status bar background color to dark gray
set -g status-bg colour235

# Changing the prefix to Control-a
set-option -g prefix C-a

# Control-t to create a new window 
bind -n C-t new-window -a -c '{pane_current_path}'

# Navigate windows using shift and arrows
bind -n S-Right next
bind -n S-Left prev
bind -n C-S-Left  swap-window -t -1
bind -n C-S-Right swap-window -t +1

# Reload the config 
bind r source-file ~/.tmux.conf

# Nested tmux navigation
bind -n S-up \
  send-keys M-F12 \; \
  set -qg status-bg colour250 \; \
  unbind -n S-left \; \
  unbind -n S-right \; \
  unbind -n S-C-left \; \
  unbind -n S-C-right \; \
  unbind -n C-t \; \
  set -qg prefix C-b
bind -n S-down \
  send-keys M-F11 \; \
  set -qg status-bg colour235 \; \
  bind -n S-left  prev \; \
  bind -n S-right next \; \
  bind -n S-C-left swap-window -t -1 \; \
  bind -n S-C-right swap-window -t +1 \; \
  bind -n C-t new-window -a -c "#{pane_current_path}" \; \
  set -qg prefix C-a

run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Split panes vertically and horizontally using <prefix> v / h
bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

bind S set synchronize-panes
