#! /usr/bin/env bash

# default editor to neovim
export EDITOR="nvim"

# default shell to bash
export SHELL=/bin/bash

# is the shell running interactively
case "$-" in
  *i*) INTERACTIVE_SHELL=1
esac

# allows killing process with all its children
killp() {

  if [ $# -eq 0 ]; then
    echo "The command killp() needs an argument, but none was provided!"
    return
  else
    pes=$1
  fi

  for child in $(ps -o pid,ppid -ax | \
    awk "{ if ( \$2 == $pes ) { print \$1 }}")
    do
      # echo "Killing child process $child because ppid = $pes"
      killp $child
    done

# echo "killing $1"
kill -9 "$1" > /dev/null 2> /dev/null
}

## --------------------------------------------------------------
## |                        tmux aliases                        |
## --------------------------------------------------------------

# set the TMUX_BIN, prefer the user-compiled one
[ -f /usr/local/bin/tmux ] && export TMUX_BIN=/usr/local/bin/tmux
[ ! -f /usr/local/bin/tmux ] && export TMUX_BIN=/usr/bin/tmux

forceKillTmuxSession() {

  num=`$TMUX_BIN ls 2> /dev/null | grep "$1" | wc -l`
  if [ "$num" -gt "0" ]; then

    pids=`tmux list-panes -s -t "$1" -F "#{pane_pid} #{pane_current_command}" | grep -v tmux | awk '{print $1}'`

    for pid in "$pids"; do
      killp "$pid"
    done

    $TMUX_BIN kill-session -t "$1"

  fi
}

# #}

# #{ quitTmuxSession()

quitTmuxSession() {

  if [ ! -z "$TMUX" ]; then

    echo "killing session"
    pids=`tmux list-panes -s -F "#{pane_pid} #{pane_current_command}" | grep -v tmux | awk {'print $1'}`

    for pid in $pids; do
      killp "$pid" &
    done

    SESSION_NAME=`tmux display-message -p '#S'`
    tmux kill-session -t "$SESSION_NAME"

  else

    exit

  fi
}

# running new tmux (or attaching) with session name derived from parent bash pid
runTmux() {

  SESSION_NAME="T$BASHPID"

  # try to find session with the correct session id (based on the bashs PID)
  EXISTING_SESSION=`$TMUX_BIN ls 2> /dev/null | grep "$SESSION_NAME" | wc -l`

  if [ "$EXISTING_SESSION" -gt "0" ]; then

    # if such session exists, attach to it
    $TMUX_BIN -2 attach-session -t "$SESSION_NAME"

  else

    # if such session does not exist, create it
    $TMUX_BIN new-session -s "$SESSION_NAME"

  fi
}

# load tmux automatically
if [ ! -z "$INTERACTIVE_SHELL" ]; then # when loaded interactively, run tmux
  if command -v $TMUX_BIN>/dev/null; then
    if [ "$RUN_TMUX" = "true" ]; then
      [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && runTmux
    fi
  fi
fi
# [[ $TERM != "screen" ]] && exec tmux
# testing chezmoi
